Redhat installer: make work with RHEL 6.4

diff --git a/installers/redhat/6/post_install.erb b/installers/redhat/6/post_install.erb
--- a/installers/redhat/6/post_install.erb
+++ b/installers/redhat/6/post_install.erb
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+exec >> /var/log/razor.log 2>&1
+
+echo "Starting post_install"
+
 # Wait for network to come up when using NetworkManager.
 if service NetworkManager status >/dev/null 2>&1 && type -P nm-online; then
     nm-online -q --timeout=10 || nm-online -q -x --timeout=30
@@ -21,21 +25,25 @@ grep -v '^127\.0\.0\.1.*' /etc/hosts- | grep '^127\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.
 grep -v '^127\.0\.0\.1.*' /etc/hosts- | grep '^127\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}.*' | tail -n +2 >> /etc/hosts
 grep -v '^127\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}.*' /etc/hosts- >> /etc/hosts
 
-[ "$?" -eq 0 ] && curl <%= log_url("set_hostname_ok") %> || curl <%= log_url("set_hostname_fail", :error) %>
-
-# Need to add the Puppetlabs repo
-rpm -i http://yum.puppetlabs.com/el/6/products/x86_64/puppetlabs-release-6-6.noarch.rpm
-[ "$?" -eq 0 ] && curl <%= log_url("repo_install_ok") %> || curl <%= log_url("repo_install_fail", :error) %>
-
-# Install requirements
-yum -y --enablerepo=base install rubygems facter
-[ "$?" -eq 0 ] && curl <%= log_url("yum_install_ok") %> || curl <%= log_url("yum_install_fail", :error) %>
+[ "$?" -eq 0 ] || curl -s <%= log_url("set_hostname_fail", :error) %>
 
 # Get current IP
-node_ip=`facter ipaddress`
+node_ip=$(ip addr show eth0 | awk '/inet / { sub("/[0-9]+$", "", $2); print $2 }')
+echo IP is $node_ip
+
 # Send IP up
-curl <%= store_url("ip" => "$node_ip") %>
-# get final script
-curl <%= file_url("os_complete") %> | sh
-# Send final state
-curl <%= log_url("os_boot_done") %> &
+curl -s <%= store_url("ip" => "$node_ip") %>
+
+cat <<EOF > /etc/motd
+Installed by Razor using <%= installer.label %> - <%= installer.description %>
+Image: <%= image_url %>
+Node: <%= node_url %>
+Install log: /var/log/razor.log
+EOF
+
+sed -i '/razor_postinstall/d' /etc/rc.local
+
+curl -s <%= broker_install_url %> | bash
+
+# We are done
+curl -s <%= stage_done_url("finished") %>
