Report "stage-done" for brokers
This changes the stock brokers to cause a note to go
into the node's log that the broker has finished and
the node is transitioned out of Razor.

Fixes https://tickets.puppetlabs.com/browse/RAZOR-357

diff --git a/brokers/puppet-pe.broker/install.erb b/brokers/puppet-pe.broker/install.erb
--- a/brokers/puppet-pe.broker/install.erb
+++ b/brokers/puppet-pe.broker/install.erb
@@ -25,5 +25,14 @@ fi
 
 bash /root/install.bash || fail "Error running /root/install.bash"
 
+# Log that the broker is finished.
+if cmd curl; then
+    curl -sL "<%= stage_done_url %>" || fail "curl failed to log broker completion"
+elif cmd wget; then
+    wget -qO- "<%= stage_done_url %>" || fail "wget failed to log broker completion" &> /dev/null
+else
+    warn "neither curl nor wget installed; cannot log completion of broker"
+fi
+
 # ...and we should be good.
 exit 0
diff --git a/brokers/puppet.broker/install.erb b/brokers/puppet.broker/install.erb
--- a/brokers/puppet.broker/install.erb
+++ b/brokers/puppet.broker/install.erb
@@ -153,3 +153,12 @@ case "${flavour}" in
         fail "I don't know what flavour distribution '${flavour}' is, sorry."
         ;;
 esac
+
+# Log that the broker is finished.
+if cmd curl; then
+    curl -sL "<%= stage_done_url %>" || fail "curl failed to log broker completion"
+elif cmd wget; then
+    wget -qO- "<%= stage_done_url %>" || fail "wget failed to log broker completion" &> /dev/null
+else
+    warn "neither curl nor wget installed; cannot log completion of broker"
+fi
