Better error detection when using curl to download script
curl, by default, will return successfully even if the server sends back some
error codes that -- in practice -- we really want to fail.  This bumps it over
to exiting with error on more of those failures, and hopefully getting less
confusing apparently success.

Signed-off-by: Daniel Pittman <daniel@rimspace.net>

diff --git a/brokers/puppet-pe.broker/install.erb b/brokers/puppet-pe.broker/install.erb
--- a/brokers/puppet-pe.broker/install.erb
+++ b/brokers/puppet-pe.broker/install.erb
@@ -16,7 +16,7 @@ url="https://<%= (broker[:server] || 'puppet') %>:8140/packages/<%= broker[:vers
 
 # Now, figure out how to download and run the script we need...
 if cmd curl; then
-    curl -kLo /root/install.bash "${url}" || fail "curl failed to get ${url}"
+    curl -fSkLo /root/install.bash "${url}" || fail "curl failed to get ${url}"
 elif cmd wget; then
     wget --no-check-certificate -O /root/install.bash "${url}" || fail "wget failed to get ${url}"
 else
