Add message when user logs in that a broker run failed
For https://tickets.puppetlabs.com/browse/RAZOR-519

diff --git a/tasks/common/os_complete.erb b/tasks/common/os_complete.erb
--- a/tasks/common/os_complete.erb
+++ b/tasks/common/os_complete.erb
@@ -9,3 +9,7 @@ EOF
 sed -i '/razor_postinstall/d' /etc/rc.d/rc.local
 
 curl -s <%= broker_install_url %> | /bin/bash
+
+if [ $? -ne 0 ]; then
+    echo "Broker run failed; see /var/log/razor.log for more details" >> /etc/motd
+fi
diff --git a/tasks/debian.task/os_complete.erb b/tasks/debian.task/os_complete.erb
--- a/tasks/debian.task/os_complete.erb
+++ b/tasks/debian.task/os_complete.erb
@@ -7,3 +7,6 @@ echo Node: <%= node_url %> >> /tmp/razor_complete.log
 sed -i '/razor_postinstall/d' /etc/rc.local
 
 curl <%= broker_install_url %> | bash
+if [ $? -ne 0 ]; then
+    echo "Broker run failed; see /var/log/razor.log for more details" >> /tmp/razor_complete.log
+fi
